databases:
- engine: PG
  name: db
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
jobs:
- build_command: composer install --no-dev --optimize-autoloader
  envs:
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:Q+n4jVk+bthSgj0ZxNaOoituzQD42K6n:SLo5be/KOC2oGPq3LxPqjAH+6uQRfmxwoZrPXrfuKj/UieA2RlmQApH85fPHjFz661yM9rIXfK2VK2pLh6L2gyIA7Q==]
  - key: DB_CONNECTION
    scope: RUN_AND_BUILD_TIME
    value: pgsql
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  - key: DB_DATABASE
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: DB_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:tzJ98gyAmSP1WsEHzGow8+QAo4Lb4KP0:eYGxNTU+WPAUNsQTGUdkDN74F+ZBAITlbM7067Kl]
  github:
    branch: main
    repo: jmasakolo/ICT-Asset-Management-
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  kind: POST_DEPLOY
  name: migrate
  run_command: php artisan migrate --force
name: ict-asset-management
region: syd
services:
- build_command: composer install --no-dev --optimize-autoloader && npm ci && npm
    run build
  envs:
  - key: APP_NAME
    scope: RUN_AND_BUILD_TIME
    value: ICT Asset Management
  - key: APP_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: APP_DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:BYTAej2F8sRAG9OMJRpf1qg72iBngbit:GefKfdToY16YoxezmkwhsyhdBTJr5Vm/5S9yHMydeOSmDeP2S/vPefkVB7OphE/AADKPIM9MbJq/f5DoGnt2hWhZpQ==]
  - key: APP_LOCALE
    scope: RUN_AND_BUILD_TIME
    value: en
  - key: APP_FALLBACK_LOCALE
    scope: RUN_AND_BUILD_TIME
    value: en
  - key: LOG_CHANNEL
    scope: RUN_AND_BUILD_TIME
    value: stderr
  - key: LOG_LEVEL
    scope: RUN_AND_BUILD_TIME
    value: error
  - key: DB_CONNECTION
    scope: RUN_AND_BUILD_TIME
    value: pgsql
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  - key: DB_DATABASE
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: DB_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:gdvfopd3dMoHYDHgZkHF3z/8FGvMXrkO:wOoVoOV5FfInO0UEHBZ1vLW+N1b6p27zkFX+b8Fr]
  - key: SESSION_DRIVER
    scope: RUN_AND_BUILD_TIME
    value: database
  - key: SESSION_LIFETIME
    scope: RUN_AND_BUILD_TIME
    value: "60"
  - key: CACHE_STORE
    scope: RUN_AND_BUILD_TIME
    value: database
  - key: QUEUE_CONNECTION
    scope: RUN_AND_BUILD_TIME
    value: database
  - key: BCRYPT_ROUNDS
    scope: RUN_AND_BUILD_TIME
    value: "12"
  - key: FILESYSTEM_DISK
    scope: RUN_AND_BUILD_TIME
    value: local
  github:
    branch: main
    deploy_on_push: true
    repo: jmasakolo/ICT-Asset-Management-
  http_port: 80
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: web
  run_command: heroku-php-apache2 public/
